### ISSUE TITLE
Define listening address

### ISSUE THREAD

**Issue by Sqozz** [jcoglan/restore#32]
Hi all,
is there a way to tell restore, that it should only listen on 127.0.0.1?
I've tried "host: 127.0.0.1" in the http-part of the config but it seems, that this gets ignored.

**Comment by Sqozz** [comment]
Okay, i figured out that restore passes the port directly to the server.listen method of node (see: https://nodejs.org/api/http.html). So i was able to create a unix-socket with a unix-path as "port" in the restore config. It whould be nice, if you caught this with a different config-option like "unix" or something like that, because "http: { port: "/tmp/restore.socket" }" is not generally intelligible ;)

**Comment by jcoglan** [comment]
I'm really sorry for replying so late to this, but it is fixed in b19f94a.
