### ISSUE TITLE
Error - "status is not defined"

### ISSUE THREAD

**Issue by lbarman** [jcoglan/restore#33]
Hi, I know it sounds more like a problem on my side than on the code, but I'm unable to run the basic script given here : https://www.npmjs.com/package/restore under "Usage"

I run ubuntu 14.04, I simply did "apt-get install nodejs", "npm install restore", then I created a file with the contents given, and did "node myScript.js". I'm completely unable to load anything from the browser, and on the server side, the script crashes with the following error message.

Any ideas ? Sorry to bother you but I'm new to NodeJS, I hope is it not a basic error from my side ;)

----------------------------------------------------------------
root@RED-SERVER:/var/www_nodejs# node restore.js

/var/www_nodejs/node_modules/restore/node_modules/ejs/lib/ejs.js:236
  throw err;
        ^
ReferenceError: ejs:1
 >> 1| <p class="status"><%= status %></p>
    2| <p class="message"><%= message %></p>
    3|
    4|

status is not defined
    at eval (eval at <anonymous> (/var/www_nodejs/node_modules/restore/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:9:28)
    at /var/www_nodejs/node_modules/restore/node_modules/ejs/lib/ejs.js:482:14
    at Object.exports.render (/var/www_nodejs/node_modules/restore/node_modules/ejs/lib/ejs.js:316:13)
    at Controller.renderHTML (/var/www_nodejs/node_modules/restore/lib/controllers/base.js:111:17)
    at Controller.errorPage (/var/www_nodejs/node_modules/restore/lib/controllers/base.js:124:8)
    at Domain.<anonymous> (/var/www_nodejs/node_modules/restore/lib/restore.js:32:43)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:263:29)

**Comment by silverbucket** [comment]
Hi @lbarman are you sure you're using the latest code and have a fresh npm install? @skddc and I had this issue a while back but I believe it was a combination of bug and upstream error. (if I remember correctly).

**Comment by jcoglan** [comment]
Is this fixed in `master`? Can I close this issue?

**Comment by skddc** [comment]
Yes, this is fixed in master. The NPM release is broken currently. See https://github.com/jcoglan/restore/issues/34

**Comment by jcoglan** [comment]
I'm closing this issue because I believe it is fixed in `master`, which will shortly be released. If it still in issue, then please do reopen this issue :)
