### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by GAZ082** [jcoglan/restore#46]

**Comment by jcoglan** [comment]
Without any more information about your exactly concerns, it's hard to meaningfully answer this question. The only response I typically give to questions like this is that, as stated in the license, the software is provided as-is.

**Comment by GAZ082** [comment]
I fund unsettling that the last commit was 2 years ago, just that.

**Comment by thornjad** [comment]
@GAZ082 Check out https://github.com/remotestorage/armadietto

**Comment by GAZ082** [comment]
@Raindeer44 thanks for a useful, well put response.
